name: eShop build

on:
  push:
    paths:
    - 'src/Services/Coupon/**'
    branches: [ main ]

env:
  IMAGE_NAME: coupon.api
  TAG: linux-latest
  CONTEXT_PATH: .
  DOCKER_FILE_PATH: src/Services/Coupon/Coupon.API/Dockerfile.acr

jobs:
  build-and-push-docker-image:
    runs-on: ubuntu-latest
    steps:
    - name: Get code from the repository
      uses: actions/checkout@v1
      with:
        ref: main

    - name: Build and push Docker image
      uses: docker/build-push-action@v1.1.0
      with:
        username: ${{ secrets.REGISTRY_USERNAME }}
        password:  ${{ secrets.REGISTRY_PASSWORD }}
        registry: ${{ secrets.REGISTRY_LOGIN_SERVER }}
        path:  ${{ env.CONTEXT_PATH }}
        dockerfile: ${{ format('{0}/{1}', env.CONTEXT_PATH, env.DOCKER_FILE_PATH) }}
        repository:  ${{ env.IMAGE_NAME }}
        tags: ${{ env.TAG }}
        push: true
